package entities.ids.table;

import jakarta.persistence.*;

@Entity
public class EntityBWithIdGeneratedFromTable {

    @TableGenerator(name = "generatorNameB", table = "ID_GENERATOR", pkColumnName = "ENTITY", pkColumnValue = "B", valueColumnName = "LAST_VALUE")
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE, generator = "generatorNameB")
    private Integer id;

    public Integer getId() {
        return id;
    }

    //  no need to define a setter since ID is generated by the database
    // public void setId(Long id) { this.id = id; }

}
