package entities.ids.sequence;

import javax.persistence.*;

@Entity
@SequenceGenerator(name = "generatorName", sequenceName = "ids")
public class EntityWithIdSequence {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generatorName")
    private Long id;

    public Long getId() {
        return id;
    }

    // no need to define a setter since ID is generated by the database
    // public void setId(Long id) { this.id = id; }

}
