package entities.ids.table;

import javax.persistence.*;

@Entity
public class EntityIdA {

    @TableGenerator(name = "generatorNameA", table = "ID_GENERATOR", pkColumnName = "ENTITY", pkColumnValue = "A", valueColumnName = "LAST_VALUE")
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE, generator = "generatorNameA")
    private Integer id;

    @Column
    private String name;

    public Integer getId() {
        return id;
    }

    // TODO no need to define a setter since ID is generated by the database
    // public void setId(Long id) { this.id = id; }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
